//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interlacer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRes_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interlacer.StringRes_EN", typeof(StringRes_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add (+).
        /// </summary>
        internal static string addPicTooltip {
            get {
                return ResourceManager.GetString("addPicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some positions for alignment lines are checked, but frame width is zero.
        ///Do you wish to continue?.
        /// </summary>
        internal static string alignLinesWarningMessage {
            get {
                return ResourceManager.GetString("alignLinesWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No positions for alignment lines are checked, but frame width is greater than zero.
        ///Do you wish to continue?.
        /// </summary>
        internal static string alignLinesWarningMessage2 {
            get {
                return ResourceManager.GetString("alignLinesWarningMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string alignLinesWarningMessageName {
            get {
                return ResourceManager.GetString("alignLinesWarningMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all (Ctrl + E).
        /// </summary>
        internal static string clearAllTooltip {
            get {
                return ResourceManager.GetString("clearAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string clearListMessage {
            get {
                return ResourceManager.GetString("clearListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        internal static string clearListMessageName {
            get {
                return ResourceManager.GetString("clearListMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file {0} may be corrupted..
        /// </summary>
        internal static string configFileCorruptError {
            get {
                return ResourceManager.GetString("configFileCorruptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl + D).
        /// </summary>
        internal static string copyPicTooltip {
            get {
                return ResourceManager.GetString("copyPicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string doneMessage {
            get {
                return ResourceManager.GetString("doneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic resolution of printing machine. Typical values are 600 DPI for HP and Canon printers, 720 DPI for Epson printers.
        ///(default 0).
        /// </summary>
        internal static string dpiToolTip {
            get {
                return ResourceManager.GetString("dpiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of images is empty.
        /// </summary>
        internal static string emptyListError {
            get {
                return ResourceManager.GetString("emptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These parameters have false values:.
        /// </summary>
        internal static string falseParamsHeadline {
            get {
                return ResourceManager.GetString("falseParamsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False interlacing parameters.
        /// </summary>
        internal static string falseParamsMessageName {
            get {
                return ResourceManager.GetString("falseParamsMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be opened. File probably does not exist..
        /// </summary>
        internal static string fileNotFoundError {
            get {
                return ResourceManager.GetString("fileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenticules are positioned horizontally, that means image is changing while view is changing from down to top. CANNOT BE USED for 3D..
        /// </summary>
        internal static string horizontalLenticuleOrientation {
            get {
                return ResourceManager.GetString("horizontalLenticuleOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image dimensions differ. Do you want to crop them to minimum width and minimum height?.
        /// </summary>
        internal static string imageDimensionError {
            get {
                return ResourceManager.GetString("imageDimensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be loaded..
        /// </summary>
        internal static string imageLoadError {
            get {
                return ResourceManager.GetString("imageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image {0} could not be saved..
        /// </summary>
        internal static string imageSaveError {
            get {
                return ResourceManager.GetString("imageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be saved. Check writing privileges and make sure there is enough space..
        /// </summary>
        internal static string imageSaveError2 {
            get {
                return ResourceManager.GetString("imageSaveError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlacing failed. Check interlacing parameters..
        /// </summary>
        internal static string interlacingError {
            get {
                return ResourceManager.GetString("interlacingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When field is checked, both height and width is being changed while keeping their aspect ratio.
        ///(default ON).
        /// </summary>
        internal static string keepAspectRatioToolTip {
            get {
                return ResourceManager.GetString("keepAspectRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string langCzech {
            get {
                return ResourceManager.GetString("langCzech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading graphics library.
        ///Make sure Visual C++ Redistributable is installed..
        /// </summary>
        internal static string libraryLoadError {
            get {
                return ResourceManager.GetString("libraryLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        internal static string loadTooltip {
            get {
                return ResourceManager.GetString("loadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual span of lenticules obtained by so called pitchtest. Typical values are between 20 and 100..
        /// </summary>
        internal static string lpiToolTip {
            get {
                return ResourceManager.GetString("lpiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amout of images, that can be put into lenticule image. Ideally, there is exactly that amout of images, whereas some images can be repeated. If maximum amout is 18, it´s appropriate to put 18 different views on the scene when doing 3D images. When doing flip of two images, it´s appropriate to use first image 9 times and second image 9 times as well.  If maximum amout of images is very distant from whole number (etc. 14.6), chosen printer isn´t appropriate for chosen lenticule material..
        /// </summary>
        internal static string maxImagesUnderLenticuleToolTip {
            get {
                return ResourceManager.GetString("maxImagesUnderLenticuleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory..
        /// </summary>
        internal static string memoryError {
            get {
                return ResourceManager.GetString("memoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down (Ctrl + down arrow).
        /// </summary>
        internal static string moveDownTooltip {
            get {
                return ResourceManager.GetString("moveDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up (Ctrl + up arrow).
        /// </summary>
        internal static string moveUpTooltip {
            get {
                return ResourceManager.GetString("moveUpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string nameListView {
            get {
                return ResourceManager.GetString("nameListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string orderListView {
            get {
                return ResourceManager.GetString("orderListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height of output image. Final image may contain alignment lines and be higher.
        ///(default 0).
        /// </summary>
        internal static string outputImageHeightToolTip {
            get {
                return ResourceManager.GetString("outputImageHeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of output image. Final image may contain alignment lines and be wider.
        ///(default 0).
        /// </summary>
        internal static string outputImageWidthToolTip {
            get {
                return ResourceManager.GetString("outputImageWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string pathListView {
            get {
                return ResourceManager.GetString("pathListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview could not be created.
        /// </summary>
        internal static string previewError {
            get {
                return ResourceManager.GetString("previewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic (default).
        /// </summary>
        internal static string printParamAdjustmentFilterCubic {
            get {
                return ResourceManager.GetString("printParamAdjustmentFilterCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        internal static string printParamAdjustmentFilterLanczos {
            get {
                return ResourceManager.GetString("printParamAdjustmentFilterLanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        internal static string printParamAdjustmentFilterLinear {
            get {
                return ResourceManager.GetString("printParamAdjustmentFilterLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest neighbour.
        /// </summary>
        internal static string printParamAdjustmentFilterNearestNeighbor {
            get {
                return ResourceManager.GetString("printParamAdjustmentFilterNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic (3D, animation, flip) (default)
        ///Lanczos (3D, animation, flip)
        ///Linear (3D, animation, flip)
        ///Nearest neighbour (flip).
        /// </summary>
        internal static string printParamAdjustmentToolTip {
            get {
                return ResourceManager.GetString("printParamAdjustmentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove (Del).
        /// </summary>
        internal static string removePicTooltip {
            get {
                return ResourceManager.GetString("removePicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace image (Ctrl + Q).
        /// </summary>
        internal static string replaceTooltip {
            get {
                return ResourceManager.GetString("replaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic (best) 
        ///(default).
        /// </summary>
        internal static string resizeFilterCubic {
            get {
                return ResourceManager.GetString("resizeFilterCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        internal static string resizeFilterLanczos {
            get {
                return ResourceManager.GetString("resizeFilterLanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        internal static string resizeFilterLinear {
            get {
                return ResourceManager.GetString("resizeFilterLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest neighbour.
        /// </summary>
        internal static string resizeFilterNearestNeighbor {
            get {
                return ResourceManager.GetString("resizeFilterNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse list (Ctrl + R).
        /// </summary>
        internal static string revertTooltip {
            get {
                return ResourceManager.GetString("revertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string saveTooltip {
            get {
                return ResourceManager.GetString("saveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort images by their ending number (Ctrl + S).
        /// </summary>
        internal static string sortTooltip {
            get {
                return ResourceManager.GetString("sortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        internal static string unitsInches {
            get {
                return ResourceManager.GetString("unitsInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenticules are positioned vertically, that means image is changing while view is changing from left to right. 
        ///(default).
        /// </summary>
        internal static string verticalLenticuleOrientation {
            get {
                return ResourceManager.GetString("verticalLenticuleOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File  {0} has wrong format..
        /// </summary>
        internal static string wrongFormatError {
            get {
                return ResourceManager.GetString("wrongFormatError", resourceCulture);
            }
        }
    }
}
