//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interlacer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRes_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interlacer.StringRes_CZ", typeof(StringRes_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+)
        ///Přidá snímek do lentikulárního obrázku.
        /// </summary>
        internal static string addPicTooltip {
            get {
                return ResourceManager.GetString("addPicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šířka pasovacích pruhů. Obvykle několik milimetrů.
        ///(default 0).
        /// </summary>
        internal static string aligmentWidthToolTip {
            get {
                return ResourceManager.GetString("aligmentWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jsou zaškrtlé některé pozice vodících čar, ale šířka rámečku je nula.
        ///Chcete pokračovat?.
        /// </summary>
        internal static string alignLinesWarningMessage {
            get {
                return ResourceManager.GetString("alignLinesWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejsou zaškrtlé žádné pozice vodících čar, ale šířka rámečku je větší než nula.
        ///Chcete pokračovat?.
        /// </summary>
        internal static string alignLinesWarningMessage2 {
            get {
                return ResourceManager.GetString("alignLinesWarningMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varování.
        /// </summary>
        internal static string alignLinesWarningMessageName {
            get {
                return ResourceManager.GetString("alignLinesWarningMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dolní
        ///(default OFF).
        /// </summary>
        internal static string bottomLinesToolTip {
            get {
                return ResourceManager.GetString("bottomLinesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čárky pasovacích pruhů leží uprostřed čočkek. Při pasování výtisku na  lentikulární materiál je barva pasovacího pruhu vidět při pohledu zpředu.  Ideální pro 3-D.
        ///(default).
        /// </summary>
        internal static string centerAlignmentToolTip {
            get {
                return ResourceManager.GetString("centerAlignmentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl + E)
        ///Odstraní ze seznamu všechny snímky..
        /// </summary>
        internal static string clearAllTooltip {
            get {
                return ResourceManager.GetString("clearAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jste si jistí?.
        /// </summary>
        internal static string clearListMessage {
            get {
                return ResourceManager.GetString("clearListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat list.
        /// </summary>
        internal static string clearListMessageName {
            get {
                return ResourceManager.GetString("clearListMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurační soubor {0} je pravděpodobně poškozen..
        /// </summary>
        internal static string configFileCorruptError {
            get {
                return ResourceManager.GetString("configFileCorruptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl + D)
        ///Zvolený snímek se duplikuje tolikrát, jaké je číslo v &quot;Počtu kopií&quot;.
        /// </summary>
        internal static string copyPicTooltip {
            get {
                return ResourceManager.GetString("copyPicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotovo.
        /// </summary>
        internal static string doneMessage {
            get {
                return ResourceManager.GetString("doneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní rozlišení tiskového stroje. Typické hodnoty jsou 600 DPI pro  tiskárny HP a Canon, 720 DPI pro tiskárny Epson.
        ///(default 0).
        /// </summary>
        internal static string dpiToolTip {
            get {
                return ResourceManager.GetString("dpiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čárky pasovacích pruhů leží na hranici mezi čočkami. Při pasování výtisku  na lentikulární materiál je barva
        /// pasovacího pruhu vidět při pohledu ze  strany..
        /// </summary>
        internal static string edgeAlignmentToolTip {
            get {
                return ResourceManager.GetString("edgeAlignmentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam obrázků je prázdný..
        /// </summary>
        internal static string emptyListError {
            get {
                return ResourceManager.GetString("emptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyto parametry jsou špatné zadány:
        ///.
        /// </summary>
        internal static string falseParamsHeadline {
            get {
                return ResourceManager.GetString("falseParamsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Špatné parametry prokládání.
        /// </summary>
        internal static string falseParamsMessageName {
            get {
                return ResourceManager.GetString("falseParamsMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} se nepodařilo otevřít. 
        ///Soubor pravděpodobně neexistuje..
        /// </summary>
        internal static string fileNotFoundError {
            get {
                return ResourceManager.GetString("fileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výška tisku včetně vodicích čar..
        /// </summary>
        internal static string heightFinalSize {
            get {
                return ResourceManager.GetString("heightFinalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lentikule jsou umístěny vodorovně, obrázek se tedy mění při změně pohledu  shora dolů. Ideální
        /// pro výměnu a animaci, NEPOUŽITELNÉ pro 3D..
        /// </summary>
        internal static string horizontalLenticuleOrientation {
            get {
                return ResourceManager.GetString("horizontalLenticuleOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrázky nejsou stejně velké. Chcete je oříznout na nejmenší šířku a nejmenší výšku?.
        /// </summary>
        internal static string imageDimensionError {
            get {
                return ResourceManager.GetString("imageDimensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} se nepodařilo načíst..
        /// </summary>
        internal static string imageLoadError {
            get {
                return ResourceManager.GetString("imageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrázek {0} se nepodařilo uložit..
        /// </summary>
        internal static string imageSaveError {
            get {
                return ResourceManager.GetString("imageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} se nepodařilo uložit. Překontrolujte zda máte právo zápisu, nebo dostatek místa..
        /// </summary>
        internal static string imageSaveError2 {
            get {
                return ResourceManager.GetString("imageSaveError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prokládání selhalo. Pravděpodobnou příčinou je chybné nastavení prokládacích parametrů. Zkontrolujte,
        /// zda některý z parametrů není nulový, příliš malý či příliš velký..
        /// </summary>
        internal static string interlacingError {
            get {
                return ResourceManager.GetString("interlacingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při zaškrtnutém poli se výška a šířka obrázku mění souběžně při zachování  poměru stran.
        ///(default ON).
        /// </summary>
        internal static string keepAspectRatioToolTip {
            get {
                return ResourceManager.GetString("keepAspectRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čeština.
        /// </summary>
        internal static string langCzech {
            get {
                return ResourceManager.GetString("langCzech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angličtina.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levý
        ///(default OFF).
        /// </summary>
        internal static string leftLinesToolTip {
            get {
                return ResourceManager.GetString("leftLinesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při načítání grafické knihovny.
        ///Pravděpodobnou příčinou je chybějící Visual C++ Redistributable.
        /// </summary>
        internal static string libraryLoadError {
            get {
                return ResourceManager.GetString("libraryLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barva prostoru mezi čárkami pasovacích pruhů. Typicky bílá.
        ///(default bílá).
        /// </summary>
        internal static string lineBackgroundColorToolTip {
            get {
                return ResourceManager.GetString("lineBackgroundColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barva čárek pasovacích pruhů. Typicky černá.
        ///(default černá).
        /// </summary>
        internal static string lineColorToolTip {
            get {
                return ResourceManager.GetString("lineColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odsazení pruhů od obrázku. Obvykle nula až 5 milimetrů. Hodnota větší než  nula je vhodná při ořezávání 
        ///finálního lentikulárního tisku.
        ///(default 0).
        /// </summary>
        internal static string linesIndentToolTip {
            get {
                return ResourceManager.GetString("linesIndentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tloušťka čárek v pasovacích pruzích. Malé hodnoty jsou vhodné pro přesné  pasování, ale kladou vyšší nároky na tisk.
        ///(default 25 %).
        /// </summary>
        internal static string lineWidthGroupBox {
            get {
                return ResourceManager.GetString("lineWidthGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst projekt.
        /// </summary>
        internal static string loadTooltip {
            get {
                return ResourceManager.GetString("loadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizuální rozteč čoček zjištěná tzv. pitchtestem. Typické hodnoty jsou  přibližně mezi 20 a 100.
        ///(default 0).
        /// </summary>
        internal static string lpiToolTip {
            get {
                return ResourceManager.GetString("lpiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximální počet snímků, který lze umístit do lentikulárního obrázku. V  ideálním případě je v lentikulárním
        /// obrázku vloženo právě tolik snímků,  přičemž některé se mohou opakovat. Je-li toto číslo například 18, je 
        /// vhodné při tvorbě 3-D obrázku vložit 18 pohledů na scénu. Při tvorbě  výměny dvou snímků je vhodné
        /// vložit první snímek 9krát, druhý rovněž  9krát. Je-li toto číslo výrazně odlišné od celého čísla (např. 14,6),
        /// není  určená tiskárna příliš vhodná pro zvolený lentikulární materiál..
        /// </summary>
        internal static string maxImagesUnderLenticuleToolTip {
            get {
                return ResourceManager.GetString("maxImagesUnderLenticuleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikace nemá k dispozici dostatek operační paměti..
        /// </summary>
        internal static string memoryError {
            get {
                return ResourceManager.GetString("memoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl + šipka dolů)
        ///Posune zvolené snímky v seznamu dolů.
        /// </summary>
        internal static string moveDownTooltip {
            get {
                return ResourceManager.GetString("moveDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl + šipka nahoru)
        ///Posune zvolené snímky v seznamu nahoru.
        /// </summary>
        internal static string moveUpTooltip {
            get {
                return ResourceManager.GetString("moveUpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string nameListView {
            get {
                return ResourceManager.GetString("nameListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pořadí.
        /// </summary>
        internal static string orderListView {
            get {
                return ResourceManager.GetString("orderListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výška výstupního obrázku. Finální výtisk může navíc obsahovat vodicí čáry  a být vyšší.
        ///(default 0).
        /// </summary>
        internal static string outputImageHeightToolTip {
            get {
                return ResourceManager.GetString("outputImageHeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šířka výstupního obrázku. Finální výtisk může navíc obsahovat vodicí čáry  a být širší.
        ///(default 0).
        /// </summary>
        internal static string outputImageWidthToolTip {
            get {
                return ResourceManager.GetString("outputImageWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta.
        /// </summary>
        internal static string pathListView {
            get {
                return ResourceManager.GetString("pathListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhled se nepodařilo vytvořit..
        /// </summary>
        internal static string previewError {
            get {
                return ResourceManager.GetString("previewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubický (default).
        /// </summary>
        internal static string printParamAdjustmentFilterCubic {
            get {
                return ResourceManager.GetString("printParamAdjustmentFilterCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        internal static string printParamAdjustmentFilterLanczos {
            get {
                return ResourceManager.GetString("printParamAdjustmentFilterLanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilineární.
        /// </summary>
        internal static string printParamAdjustmentFilterLinear {
            get {
                return ResourceManager.GetString("printParamAdjustmentFilterLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejbližší soused.
        /// </summary>
        internal static string printParamAdjustmentFilterNearestNeighbor {
            get {
                return ResourceManager.GetString("printParamAdjustmentFilterNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubický (3D, animace, výměna) (default)
        ///Lanczos (3D, animace, výměna)
        ///Bilineární (3D, animace, výměna)
        ///Nejbližší soused (výměna).
        /// </summary>
        internal static string printParamAdjustmentToolTip {
            get {
                return ResourceManager.GetString("printParamAdjustmentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Del)
        ///Odebere zvolené snímky z lentikulárního obrázku.
        /// </summary>
        internal static string removePicTooltip {
            get {
                return ResourceManager.GetString("removePicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Q)
        ///Nahradí zvolený snímek jiným snímekem z disku.
        /// </summary>
        internal static string replaceTooltip {
            get {
                return ResourceManager.GetString("replaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubický (nejlepší) 
        ///(default).
        /// </summary>
        internal static string resizeFilterCubic {
            get {
                return ResourceManager.GetString("resizeFilterCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        internal static string resizeFilterLanczos {
            get {
                return ResourceManager.GetString("resizeFilterLanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineární.
        /// </summary>
        internal static string resizeFilterLinear {
            get {
                return ResourceManager.GetString("resizeFilterLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejbližší soused.
        /// </summary>
        internal static string resizeFilterNearestNeighbor {
            get {
                return ResourceManager.GetString("resizeFilterNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl + R)
        ///Otočí seznam snímků. Užitečné zejména pro 3-D, protože snímky musí být v pořadí od nejlevějšího k nejpravějšímu.
        /// </summary>
        internal static string revertTooltip {
            get {
                return ResourceManager.GetString("revertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pravý
        ///(default OFF).
        /// </summary>
        internal static string rightLinesToolTip {
            get {
                return ResourceManager.GetString("rightLinesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit projekt.
        /// </summary>
        internal static string saveTooltip {
            get {
                return ResourceManager.GetString("saveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl + S)
        ///Seřadí seznam snímků. Užitečné zejména pro 3-D a animace, obsahují-li  jejich názvy pořadí.
        /// U 3-D nezapomeňte zkontrolovat, zda jsou snímky v  pořadí od nejlevějšího k nejpravějšímu
        /// pokud ne, použijte tlačítko  &quot;Otočit&quot;.
        /// </summary>
        internal static string sortTooltip {
            get {
                return ResourceManager.GetString("sortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horní
        ///(default OFF).
        /// </summary>
        internal static string topLinesToolTip {
            get {
                return ResourceManager.GetString("topLinesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palce.
        /// </summary>
        internal static string unitsInches {
            get {
                return ResourceManager.GetString("unitsInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lentikule jsou umístěny svisle, obrázek se tedy mění při změně pohledu  zleva doprava. Nutné pro
        /// 3D a velkoplošné lentikulární tisky, méně vhodné  pro výměnu a animaci.
        ///(default).
        /// </summary>
        internal static string verticalLenticuleOrientation {
            get {
                return ResourceManager.GetString("verticalLenticuleOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šířka tisku včetně vodicích čar..
        /// </summary>
        internal static string widthFinalSize {
            get {
                return ResourceManager.GetString("widthFinalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} má chybný formát..
        /// </summary>
        internal static string wrongFormatError {
            get {
                return ResourceManager.GetString("wrongFormatError", resourceCulture);
            }
        }
    }
}
